version: '3'
services:
  demoapp:
    container_name: demoapp
    image: docker.${SERVER_DOMAIN}/demoapp
    restart: always
    networks:
      - core
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:demoapp.${SERVER_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true

networks:
  core:
    external: true
