version: '3'
services:
  demoapp:
    container_name: demoapp
    image: docker.<your domain>/demoapp
    restart: always
    networks:
      - core
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:demoapp.<your domain>
      - com.centurylinklabs.watchtower.enable=true

networks:
  core:
    external: true
