pipeline:
  docker:
    image: plugins/docker
    repo: docker.fredriklowenhamn.com/root/demoapp
    registry: https://docker.fredriklowenhamn.com
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
