version: '3'
services:
  demoapp:
    container_name: demoapp
    image: docker.${DOMAIN}/${REPO}
    restart: always
    networks:
      - core
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:demoapp.${DOMAIN}
      - com.centurylinklabs.watchtower.enable=true

  demoapp-test:
    container_name: demoapp-test
    image: docker.${DOMAIN}/${REPO}
    restart: always
    networks:
      - core

  demo-test-proxy:
    container_name: demo-test-proxy
    image: lowet84/oauth2proxy
    labels:
      - traefik.enable=true
      - traefik.port=4180
      - traefik.frontend.rule=Host:demoapp-test.${SERVER_DOMAIN}
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=${COOKIE_SECRET}
      - OAUTH2_PROXY_COOKIE_DOMAIN=${SERVER_DOMAIN}
      - OAUTH2_PROXY_CLIENT_ID=${CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${CLIENT_SECRET}
      - SERVICE=demoapp-test:3000
      - GROUP=test
    restart: always
    networks:
      - core

networks:
  core:
    external: true
